### ISSUE TITLE
need canary upgrade tidb operator doc

### ISSUE THREAD

**Issue by shonge** [pingcap/docs-tidb-operator#1044]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
#992 

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by csuzhangxc** [comment]
I have some comments in #1043, but the PR has been merged.

**Comment by ran-huang** [comment]
@csuzhangxc My bad.😅 I can include your suggestions when I translate the PR later.
