### ISSUE TITLE
Queeny test for the new docs in v1.2

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#1069]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

We introduced some new docs recently, e.g. 
https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/deploy-tidb-cluster-across-multiple-kubernetes
https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/aggregate-multiple-cluster-monitor-data

And we should run the Queeny test for them to make sure they are user-friendly enough.

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by ran-huang** [comment]
@DanielZhangQD Any updates on this one?

**Comment by DanielZhangQD** [comment]
@ran-huang Sorry, not yet, maybe next week.
