### ISSUE TITLE
enable-tls-between-components.md should link to the relate version tidb docs

### ISSUE THREAD

**Issue by july2993** [pingcap/docs-tidb-operator#1105]
File: [/zh/enable-tls-between-components.md](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/enable-tls-between-components)

should lint to the relate version docs

It contains relate docs link
https://pingcap.com/docs/v3.0/how-to/secure/enable-tls-between-components/

**Comment by ran-huang** [comment]
Thanks. I'll update the version. 

Can you help identify the version relationship between TiDB Operator and TiDB? Is this correct:
> TiDB Operator dev -> TiDB dev
> TiDB Operator v1.1 -> TiDB v4.0
I'm not sure where we should put TiDB v5.0 though...

**Comment by july2993** [comment]
there are no hard relate tidb version between the operator, it depends on the tidb version you are deploying

dev -> dev
1.1 -> v4.1 

looks fine for me

@DanielZhangQD PTAL

**Comment by DanielZhangQD** [comment]
> there are no hard relate tidb version between the operator, it depends on the tidb version you are deploying
> 
> dev -> dev
> 1.1 -> v4.1
> 
> looks fine for me
> 
> @DanielZhangQD PTAL

It's OK.
