### ISSUE TITLE
in docs-tidb-operator/zh/benchmark-sysbench.md，i cannot understand what's your mean.

### ISSUE THREAD

**Issue by tulid** [pingcap/docs-tidb-operator#1114]
## Question
in docs-tidb-operator/zh/benchmark-sysbench.md, can you describe the steps in detail.
i cannot known what do you want to test.
which function do you want to test?
which node/pod do you want to test?
where the sysbench can be installed?
where the database can be created and how to create test database?
and so on? 

please, please, please
can you describe the steps in detail.
thanks a lot.

**Comment by ran-huang** [comment]
Hi, thank you for your question! This doc aims to test:
- the performance of TiDB on a typical public cloud platform
- the influences that the public cloud platform, network, CPU and different Pod networks have on the performance of TiDB

It offers insight into the influencing factors that affect the performance of TiDB in Kubernetes, but it's not a step-by-step guide.

If you have questions regarding the usage of TiDB, we suggest that you seek help from other TiDB users at [AskTUG](https://asktug.com/).
