### ISSUE TITLE
Incomplete command in upgrade-a-tidb-cluster

### ISSUE THREAD

**Issue by ran-huang** [pingcap/docs-tidb-operator#1141]
[File link](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/upgrade-a-tidb-cluster#%E5%BC%BA%E5%88%B6%E5%8D%87%E7%BA%A7-tidb-%E9%9B%86%E7%BE%A4). 
This command looks incomplete.
![image](https://user-images.githubusercontent.com/59654584/112278686-0d50b500-8cbe-11eb-8fc8-a2fbe1ace31a.png)

**Comment by DanielZhangQD** [comment]
@ran-huang That's the desired command.
