### ISSUE TITLE
Add more description for the cluster domain in the across Kubernetes deployment doc

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#1241]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
We request the user to configure the cluster domain for the TidbClusters in the different Kubernetes clusters, however, we should make it clear that the cluster domain configured for the TC should match with that of the Kubernetes cluster.

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by yiduoyunQ** [comment]
1. Describe what you find is inappropriate or missing in the existing docs.

I'd like to make a across cluster test, I used **operator@v1.2.0-rc.1** and followed with [doc deploy-tidb-cluster-across-multiple-kubernetes](https://docs.pingcap.com/tidb-in-kubernetes/dev/deploy-tidb-cluster-across-multiple-kubernetes#deploy-a-cluster-across-multiple-kubernetes-clusters)

The 2  TC  configurations I used directly is from:

[tidb-cluster-1](https://github.com/pingcap/tidb-operator/blob/master/examples/multi-cluster/tidb-cluster-1.yaml)
[tidb-cluster-2](https://github.com/pingcap/tidb-operator/blob/master/examples/multi-cluster/tidb-cluster-2.yaml)

Then when I deployed tidb-cluster-1, the pd pod is CrashLoopBackOff over and over

``` shell
# kubectl get po -A | grep cluster1-pd
tidb-cluster1   cluster1-pd-0                              0/1     CrashLoopBackOff   446        41h
tidb-cluster1   cluster1-pd-1                              0/1     CrashLoopBackOff   446        41h
tidb-cluster1   cluster1-pd-2                              0/1     CrashLoopBackOff   446        41h
```

The dns domain error in pod logs

``` shell
# kubectl -n tidb-cluster1 logs po/cluster1-pd-0  | tail -n 5

nslookup domain cluster1-pd-0.cluster1-pd-peer.tidb-cluster1.svc.cluster1.com failed

nslookup domain cluster1-pd-0.cluster1-pd-peer.tidb-cluster1.svc.cluster1.com failed
waiting for pd cluster ready timeout
```

I found the default DNS configuration of pd pod in /etc/hosts is `cluster1-pd-0.cluster1-pd-peer.tidb-cluster1.svc.cluster.local	cluster1-pd-0`, and `xxx svc.cluster.local cluster.local` in /etc/resolv.conf.
`cluster.local` seems be the default domain value of Kubernetes node and CM of coredns

``` shell
# cat /var/lib/kubelet/config.yaml | grep cluster.local
clusterDomain: cluster.local

# kubectl -n kube-system get cm/coredns -o yaml | grep cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
```

The special value `cluster1.com` in error message is **spec.clusterDomain** in TC configuration:

``` shell
# kubectl -n tidb-cluster1 get tc/cluster1 -o yaml | grep clusterDomain:
  clusterDomain: cluster1.com
```

So they should match with each or dns nslookup will work error.

2. Describe your suggestion or addition.

I found some suggestion about `clusterDomain` in [doc](https://docs.pingcap.com/tidb-in-kubernetes/dev/deploy-tidb-cluster-across-multiple-kubernetes#enable-the-feature-for-a-cluster-with-existing-data-and-make-it-the-initial-tidb-cluster), but it seems only a instruction of requirement for TC spec, not a instruction for Kubernetes sepcifically.
So may be adding some instruction about the relationship between spec.clusterDomain and Kubernetes DNS configuration in the doc, and some troubleshooting tips about this problem will be better and nice :)

3. Provide some reference materials (documents, websites, etc) if you could.

[kubelet configuration doc](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) with clusterDomain 
[Coredns configuration example](https://coredns.io/plugins/kubernetes/#examples)
