### ISSUE TITLE
Add doc about how to stop the components temporarily

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#1245]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
Sometimes users want to stop the TiDB components temporarily, we can leverage the `runmode: debug` annotation to do this, we can add a new section in the doc https://docs.pingcap.com/tidb-in-kubernetes/dev/tips.
The annotation can be configured in `spec.annotations` or `spec.xx.annotations`, please note that only support for PD, TiKV, and TiDB now.

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by DanielZhangQD** [comment]
For PD, you have to force upgrade it following the doc https://docs.pingcap.com/tidb-in-kubernetes/dev/upgrade-a-tidb-cluster#force-an-upgrade-of-tidb-cluster-using-tidbcluster-cr when you have to recover from the debug mode.
So to stop multiple components, the order should be:

- set annotation for TiKV/TiDB, wait for it to finish rolling update, 
- set annotation for PD

To recover:

- remove the annotation for PD and TiKV/TiDB
- force upgrade PD
- wait for the PD and TiKV/TiDB rolling update done

**Comment by KanShiori** [comment]
It's unsupported to stop the components temporarily by debug mode, so just add a tip to stop a Pod temporarily.
