### ISSUE TITLE
在 '配置 StorageClass' 文档中添加更多的命令示例

### ISSUE THREAD

**Issue by KanShiori** [pingcap/docs-tidb-operator#1253]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
文档 [Kubernetes 上的持久化存储类型配置](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/configure-storage-class#%E7%A4%BA%E4%BE%8B) 中描述的 '将新建的目录以 bind mount 方式挂载到 /mnt/disks 目录' 看起来意思是
```bash
mount --bind <dir> /mnt/disks
```
而实际上的意思是
```bash
mount --bind <dir> /mnt/disks/<dir>
```
2. Describe your suggestion or addition.
添加实际的命令示例

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by DanielZhangQD** [comment]
@KanShiori 
Thanks for reporting this issue!
The detailed commands are shown in the reference doc for `步骤`, e.g. https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/operations.md#sharing-a-disk-filesystem-by-multiple-filesystem-pvs.
