### ISSUE TITLE
Helm version is not compatible to deploy Kubernetes cluster using kind

### ISSUE THREAD

**Issue by rajeshwer** [pingcap/docs-tidb-operator#1302]
File: [/en/deploy-tidb-from-kubernetes-kind.md](https://docs.pingcap.com/tidb-in-kubernetes/v1.0/deploy-tidb-from-kubernetes-kind)
* Document Recommends Helm Client: version >= 2.11.0 and < 2.16.4
But the script will be installing helm version 3.5.0
https://github.com/rajeshwer/tidb-operator/blob/master/hack/lib.sh#L36

Error:
```Error: unknown command "init" for "helm"
Did you mean this?
	lint
Run 'helm --help' for usage.
```

* Helm versions prior to 2.17.0 have the deprecated https://kubernetes-charts.storage.googleapis.com/index.yaml as the default stable repository, which no longer resolves. The new repo is https://charts.helm.sh/stable.

    https://github.com/rajeshwer/tidb-operator/blob/master/hack/kind-cluster-build.sh#L241
    Use the --stable-repo-url argument to specify the new repository:
    ```$HELM_BIN init --stable-repo-url https://charts.helm.sh/stable --service-account tiller```

Error:
```
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```

**Comment by DanielZhangQD** [comment]
@rajeshwer Please check the latest doc here https://docs.pingcap.com/tidb-in-kubernetes/dev/get-started.
The doc for v1.0 is outdated.
