### ISSUE TITLE
Update the doc of binlog deployment

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#1320]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
https://github.com/pingcap/tidb-operator/pull/3973 has improved the lifecycle management for Pump so that the doc
https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/deploy-tidb-binlog#%E7%BC%A9%E5%AE%B9%E7%A7%BB%E9%99%A4-pumpdrainer-%E8%8A%82%E7%82%B9 should be updated.

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by DanielZhangQD** [comment]
Please also add procedure to upgrade drainer and pump.

**Comment by better0332** [comment]
> Please also add procedure to upgrade drainer and pump.

@DanielZhangQD Is Dainer not implemented yet?
