### ISSUE TITLE
optimize the description about using `BR` to restore data

### ISSUE THREAD

**Issue by KanShiori** [pingcap/docs-tidb-operator#1354]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

Doc: https://docs.pingcap.com/zh/tidb-in-kubernetes/v1.1/restore-from-pv-using-br#%E6%95%B0%E6%8D%AE%E5%BA%93%E8%B4%A6%E6%88%B7%E6%9D%83%E9%99%90

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by DanielZhangQD** [comment]
@KanShiori Could you please explain in more detail what should be optimized?
