### ISSUE TITLE
/zh/get-started.md 扣文字

### ISSUE THREAD

**Issue by IcePigZDB** [pingcap/docs-tidb-operator#1365]
File: [/zh/get-started.md](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/get-started)
[部署 TiDB 集群](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/get-started#%E9%83%A8%E7%BD%B2-tidb-%E9%9B%86%E7%BE%A4)和[部署 TiDB 集群监控](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/get-started#%E9%83%A8%E7%BD%B2-tidb-%E9%9B%86%E7%BE%A4%E7%9B%91%E6%8E%A7)中提到使用的是阿里云的镜像，`如果访问 Docker Hub 网速较慢，可以使用阿里云上的镜像：`，yaml文件中实际上用的是Ucloud~

**Comment by ran-huang** [comment]
😎 Sharp eyes. 谢谢指出！
请问你愿意提一个 PR 来修改这里的文字描述吗？

**Comment by hfxsd** [comment]
PR 已提 https://github.com/pingcap/docs-tidb-operator/pull/1499

**Comment by IcePigZDB** [comment]
thks~
