### ISSUE TITLE
configure-storage-class 文档修改建议

### ISSUE THREAD

**Issue by ben-wangz** [pingcap/docs-tidb-operator#1367]
File: [/zh/configure-storage-class.md](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/configure-storage-class)

1. **raw.githubusercontent.com** 这个域名下的资源对中国用户存在一定的限制（连接与带宽）
2. 使用了 **master** 分支的内容，而不是最新的release 分支

建议直接从代码出发，例如，
```shell
git clone --single-branch --branch v1.2.1 git@github.com:pingcap/tidb-operator.git
kubectl apply -f tidb-operator/manifests/local-dind/local-volume-provisioner.yaml
```

**Comment by DanielZhangQD** [comment]
GitHub is also very slow for us.
I think we can update our doc for the issue `使用了 master 分支的内容，而不是最新的release 分支` in the released branches.

**Comment by KanShiori** [comment]
Close by PR #1770
