### ISSUE TITLE
need configuration change guide when using customized configuration file in tidb-monitor

### ISSUE THREAD

**Issue by yiduoyunQ** [pingcap/docs-tidb-operator#1368]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
in doc https://docs.pingcap.com/tidb-in-kubernetes/stable/monitor-a-tidb-cluster#use-a-customized-configuration-file, it doesn't show how to change the configuration after deploy tidb-monitor using customized configuration file.

2. Describe your suggestion or addition.
In my test, it can be done with 2 steps:
edit the ConfigMap
delete & apply to recreate the tidb-monitor

there are 3 points need emphasize
spec.persistent 
spec.pvReclaimPolicy 
external service port will be changed

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by DanielZhangQD** [comment]
With the master branch of TiDB Operator, this should be done via editing the ConfigMap only and Prometheus will reload the config automatically after setting `spec.PrometheusReloader`.
@just1900 Please help verify this and update the examples in TiDB Operator repo to add `spec.PrometheusReloader` for all the TidbMonitor examples and update the docs.

**Comment by just1900** [comment]
It works fine after setting `spec.PrometheusReloader`, the external config get reloaded.
@yiduoyunQ sorry for the late reply, what do you mean by these 3 points?

> there are 3 points need emphasize
spec.persistent
spec.pvReclaimPolicy
external service port will be changed

**Comment by just1900** [comment]
Related pr for tidb-operator https://github.com/pingcap/tidb-operator/pull/4464
and docs https://github.com/pingcap/docs-tidb-operator/pull/1731

**Comment by yiduoyunQ** [comment]
> 

I mean if I do not use `spec.PrometheusReloader` and directly edit the ConfigMap and delete & apply to recreate the tidb-monitor, we need take attention about these 3 points.
