### ISSUE TITLE
typo in tidb-cluster.yaml

### ISSUE THREAD

**Issue by andrewpalkio** [pingcap/docs-tidb-operator#1394]
File: [/en/enable-tls-for-mysql-client.md](https://docs.pingcap.com/tidb-in-kubernetes/stable/enable-tls-for-mysql-client)

For the TiDBCluster definition inside tidb-cluster.yaml, there's a typo for namespace, its missing a 'n':

apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: ${cluster_name}
  amespace: ${namespace}

**Comment by KanShiori** [comment]
Thanks for pointing it out!
