### ISSUE TITLE
crd.yaml已不适用于k8s:v1.22.2

### ISSUE THREAD

**Issue by Cenobitor** [pingcap/docs-tidb-operator#1421]
File: [/en/get-started.md](https://docs.pingcap.com/tidb-in-kubernetes/stable/get-started)

**Comment by KanShiori** [comment]
Kubernetes 1.22 支持已经在开发中，相关 PR 可以见 TiDB Operator 仓库，预计 v1.3.0 版本支持。

**Comment by DanielZhangQD** [comment]
@Cenobitor Thanks for reporting this issue!
I will close this and we will trace the doc update in https://github.com/pingcap/docs-tidb-operator/issues/1464.
