### ISSUE TITLE
Improve the EKS deployment doc

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#1425]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
Some prerequisites in https://docs.pingcap.com/tidb-in-kubernetes/dev/prerequisites may need to be done during EKS deployment https://docs.pingcap.com/tidb-in-kubernetes/dev/deploy-on-aws-eks.

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by DanielZhangQD** [comment]
We need to set the following user data for EKS nodes ():
const userData = `#!/bin/bash -xe
# install ssm-agent
yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
# set ulimits
cat <<EOF > /etc/security/limits.d/99-tidb.conf
root        soft        nofile        1048576
root        hard        nofile        1048576
root        soft        stack         10240
EOF
`;

For the SSM to be used, the IAM role `arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore` is required for the worker nodes.

**Comment by better0332** [comment]
- EKS cluster does not need to refer to https://docs.pingcap.com/tidb-in-kubernetes/dev/prerequisites
- SSM is not a required option
- ulimits may be need
