### ISSUE TITLE
Documents needed: In the case of eks deploying tidb, upgrade the machine configuration online

### ISSUE THREAD

**Issue by wxiaoke** [pingcap/docs-tidb-operator#1432]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
Deploy TiDB with EKS, upgrade machine configuration online

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by DanielZhangQD** [comment]
@wxiaoke Do you want to migrate from r5.4xlarge to r5.8xlarge online?

**Comment by wxiaoke** [comment]
> @wxiaoke Do you want to migrate from r5.4xlarge to r5.8xlarge online?

Yes, actually,  I already do the test for that and customer also change the machine configuration online sucessfully.
Proceed as follows：
1. Create a new node group
2. Use the kubectl drain command to migrate the database instance on the node to be maintained to other nodes
3. delete the previous nodegroup

**Comment by DanielZhangQD** [comment]
Procedure is available in https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/replace-nodes-for-cloud-disk/.
