### ISSUE TITLE
Support status of HPA and VPA

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs-tidb-operator#1446]
File: [/en/faq.md](https://docs.pingcap.com/tidb-in-kubernetes/stable/faq)

I'd like to know the support status of HPA and VPA. In this page, it says " TiDB cluster does not support HPA (Horizontal Pod Autoscaling) or VPA (Vertical Pod Autoscaling)".

https://docs.pingcap.com/tidb-in-kubernetes/stable/faq#can-hpa-or-vpa-be-configured-on-tidb-components
> Can HPA or VPA be configured on TiDB components?
Currently, the TiDB cluster does not support HPA (Horizontal Pod Autoscaling) or VPA (Vertical Pod Autoscaling), because it is difficult to achieve autoscaling on stateful applications such as a database. Autoscaling can not be achieved merely by the monitoring data of CPU and memory.

On the other hand, https://docs.pingcap.com/tidb-in-kubernetes/dev/enable-tidb-cluster-auto-scaling says it is "The auto-scaling feature is in the alpha stage. ".

> The auto-scaling feature is in the alpha stage. 

For me it is not clear the differences between 'not supported' and 'in the alpha stage'.

**Comment by DanielZhangQD** [comment]
@yahonda Thanks for reporting this issue!
We will remove the description in FAQ.

**Comment by DanielZhangQD** [comment]
@zkkxu We can just remove the HPA from the FAQ.

**Comment by DanielZhangQD** [comment]
@yahonda The HPA and VPA here are the Kubernetes concepts and TiDB Operator does not support them, so the discription should be OK, WDYT?

**Comment by yahonda** [comment]
Do you mean that `TiDB Cluster Auto-scaling` does not use Kubernetes HPA and VPA features, `TiDB Cluster Auto-scaling` has its own auto-scaling mechanism?

**Comment by DanielZhangQD** [comment]
> Do you mean that `TiDB Cluster Auto-scaling` does not use Kubernetes HPA and VPA features, `TiDB Cluster Auto-scaling` has its own auto-scaling mechanism?

Yes.

**Comment by DanielZhangQD** [comment]
> If my understanding is correct (and my first understanding was incorrect), I think we can close this issue without changing anything.

OK.
