### ISSUE TITLE
Update the Prometheus and Grafana version

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#1459]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**
The version for Prometheus in TiDB Operator repo has been updated to v2.27.1 and the version of Grafana has been updated to 7.5.11, we also have to update the versions in the doc.
Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by just1900** [comment]
There are some examples still using v2.11.1 version this pr has address this. https://github.com/pingcap/tidb-operator/pull/4465
