### ISSUE TITLE
Error when creating CRD 

### ISSUE THREAD

**Issue by ithinkso0575** [pingcap/docs-tidb-operator#1464]
An error occurs when this command is executed：kubectl apply -f crd.yaml

The error message：
unable to recognize "crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

File: [/zh/deploy-tidb-operator.md](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/deploy-tidb-operator)

**Comment by KanShiori** [comment]
Is the Kubernetes version greater than 1.22?

**Comment by ithinkso0575** [comment]
Yes, the version is 1.22.4, I have seen the reply #1421, wait until v1.3.0？

**Comment by KanShiori** [comment]
Yes, or you can use the master branch, ref https://github.com/pingcap/tidb-operator/issues/4275#issuecomment-977443431
