### ISSUE TITLE
Change syntax highlight from shell to bash

### ISSUE THREAD

**Issue by ran-huang** [pingcap/docs-tidb-operator#1501]
The new docs site doesn't support ` ```shell` style code highlighting. Use ` ```bash` instead.

For the full supported language list, see https://prismjs.com/#supported-languages

**Comment by yahonda** [comment]
Opened #1514 to address it.

**Comment by ran-huang** [comment]
It has been verified that both `shell` and `bash` work on our site. I'll close this issue. Sorry for the misinformation!
