### ISSUE TITLE
Request update on AKS LoadBalancer Note

### ISSUE THREAD

**Issue by lokiloveu1** [pingcap/docs-tidb-operator#1850]
File: [/release-1.3/en/deploy-on-azure-aks.md](https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-on-azure-aks)

Hello team,

Customer is confusing about how to modify TiDB from internal load balancer to public load balancer on AKS. Our doc is not that clear to indicate the steps. I have tested and verified that deleting the annotation in the tidb-cluster.yaml file:

'''
 annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
'''

is the right step to public TiDB service to the internet.

Could you please help update the Note here so customers can understand easier:

Note
By default, TiDB LoadBalancer in tidb-cluster.yaml is set to "internal", indicating that the LoadBalancer is only accessible within the cluster virtual network, not externally. To access TiDB over the MySQL protocol, you need to use a bastion to access the internal host of the cluster or use kubectl port-forward. You can delete the "internal" schema in the tidb-cluster.yaml file to expose the LoadBalancer publicly by default. However, notice that this practice may expose TiDB to risks.

To sth like this:

Note
By default, TiDB LoadBalancer in tidb-cluster.yaml is set to "internal", indicating that the LoadBalancer is only accessible within the cluster virtual network, not externally. To access TiDB over the MySQL protocol, you need to use a bastion to access the internal host of the cluster or use kubectl port-forward. 

You can delete the annotation following in the tidb-cluster.yaml file:

 annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"

to expose the LoadBalancer publicly. However, notice that this practice may expose TiDB to risks.

中文版修订：

注意
默认情况下，tidb-cluster.yaml 文件中 TiDB 服务的 LoadBalancer 配置为 "internal"。这意味着 LoadBalancer 只能在集群虚拟网络内部访问，而不能在外部访问。要通过 MySQL 协议访问 TiDB，您需要使用一个堡垒机进入集群节点或使用 kubectl port-forward。如果您想在互联网上公开访问 TiDB，并且知晓这样做的风险，您可以在 tidb-cluster.yaml 文件中将以下注释删除：

 annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"

之后重新创建的 LoadBalancer 及其关联的TiDB服务将能够在外部访问。

Thanks for reviewing!

Let me know if you have any questions regarding to this PR. 

Loki.C  (chengqian@pingcap.com)

**Comment by yiduoyunQ** [comment]
seems [deploy-on-eks](https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-on-aws-eks#deploy) has already added this note, let me add it for deploy-on-aks, and thank you loki for the **Note**
