### ISSUE TITLE
Single quote missed

### ISSUE THREAD

**Issue by realcp1018** [pingcap/docs-tidb-operator#1865]
File: [/release-1.3/zh/pd-recover.md](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/pd-recover)

`kubectl patch tc ${cluster_name} -n ${namespace} --type merge -p '{"spec":{"pd":{"replicas": $replicas}}}`
Should be:
`kubectl patch tc ${cluster_name} -n ${namespace} --type merge -p '{"spec":{"pd":{"replicas": $replicas}}}'`

**Comment by ran-huang** [comment]
Thanks for reporting this typo! Would you like to open a PR and fix this?
