### ISSUE TITLE
use the tiup playground --pd.host 0.0.0.0 --db.host 0.0.0.0, why the tiflash throw error?

### ISSUE THREAD

**Issue by RubyKiss** [pingcap/docs-tidb-operator#2257]
image:
<a href="https://ibb.co/7rsNrv5"><img src="https://i.ibb.co/7rsNrv5/jietu.png" alt="jietu" border="0"></a>

how can i do ???????

**Comment by ran-huang** [comment]
Hi, @RubyKiss  this repository only addresses issues for the documentation. If you have any questions about using TiDB or its related tools, you can seek help or find answers from the community on [AskTUG](https://asktug.com/).
你好，这个仓库只处理文档相关的问题。如果你有任何关于如何使用 TiDB 或其相关工具的问题，可以在 [AskTUG](https://asktug.com/) 找到答案。
