### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [pingcap/docs-tidb-operator#2310]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by lilin90** [comment]
Hi @igibek, thanks for your feedback!

If you have discovered a vulnerability in a TiDB product or have encountered a security incident involving a TiDB product vulnerability, please report it to the TiDB security team at [security@pingcap.com](mailto:security@pingcap.com).

And the following situations do not qualify as security vulnerabilities:

- Physical attacks
- Social engineering attacks or proximity attacks
- Missing HTTP security headers or enabling specific HTTP methods
- Email Sender Policy Framework (SPF) issues

You can find more information at this link: https://www.pingcap.com/security

Thank you again for your attention. We look forward to more valuable bug reports from you.
