### ISSUE TITLE
Disaster recovery documentation for k8s deployment

### ISSUE THREAD

**Issue by tirsen** [pingcap/docs-tidb-operator#246]
Current disaster recovery documentation is very centered around an Ansible deployment. We need better docs for a disaster recovery on k8s.

**Comment by DanielZhangQD** [comment]
Chinese doc: https://github.com/pingcap/docs-tidb-operator/pull/245
English doc: https://github.com/pingcap/docs-tidb-operator/pull/250

**Comment by tirsen** [comment]
Wow this is really useful documentation and so quickly delivered. Thanks!
