### ISSUE TITLE
namespaces "tidb-admin" not found

### ISSUE THREAD

**Issue by coderplay** [pingcap/docs-tidb-operator#258]
File: [/zh/deploy-tidb-operator.md](https://pingcap.com/docs-cn/tidb-in-kubernetes/v1.1/deploy-tidb-operator/)

I believe both English and Chinese version have the same issue. There is no steps for creating tidb-admin namespace.

**Comment by coderplay** [comment]
```configmaps "tidb-scheduler-policy" not found, serviceaccounts "tidb-controller-manager" not found, serviceaccounts "tidb-scheduler" not found, clusterroles.rbac.authorization.k8s.io "tidb-operator:tidb-controller-manager" not found, clusterroles.rbac.authorization.k8s.io "tidb-operator:tidb-scheduler" not found, clusterrolebindings.rbac.authorization.k8s.io "tidb-operator:tidb-controller-manager" not found, clusterrolebindings.rbac.authorization.k8s.io "tidb-operator:tidb-scheduler" not found, clusterrolebindings.rbac.authorization.k8s.io "tidb-operator:kube-scheduler" not found, clusterrolebindings.rbac.authorization.k8s.io "tidb-operator:volume-scheduler" not found, deployments.apps "tidb-controller-manager" not found, deployments.apps "tidb-scheduler" not found```

Many things are not found.

**Comment by DanielZhangQD** [comment]
@coderplay Please note that the helm version required in `Helm version >= 2.11.0 and < 2.16.4` which is stated at the beginning of the document. 
Actually it should be a bug of helm 2.16.4.

**Comment by coderplay** [comment]
Got it , thank you!
