### ISSUE TITLE
incorrect instructions

### ISSUE THREAD

**Issue by coderplay** [pingcap/docs-tidb-operator#260]
File: [/en/deploy-on-general-kubernetes.md](https://pingcap.com/docs/tidb-in-kubernetes/v1.1/deploy-on-general-kubernetes/)

on step 2 on `Deploy TiDB Cluster`,  it should be `${cluster_name}/tidb-cluster.yaml` rather than a cluster name, right?

```
kubectl apply -f ${cluster_name}/tidb-cluster.yaml -n ${namespace}
```

**Comment by ran-huang** [comment]
Thanks for your feedback!
@DanielZhangQD PTAL~

**Comment by DanielZhangQD** [comment]
> /en/deploy-on-general-kubernetes.md

There could be multiple yaml files under ${cluster_name} dir, e.g. tidb-cluster.yaml and tidb-monitor.yaml, so just follow the command in the doc.

**Comment by DanielZhangQD** [comment]
@coderplay Any more questions for this issue?

**Comment by coderplay** [comment]
Nope, but I didn't get your meaning on `follow the command`.   I meant the command was incorrect.

**Comment by DanielZhangQD** [comment]
Why it's incorrect? Could you please show me the error log?
If we specify a directory to kubectl, it will create all of the yamls under that directory, and for this case, there would be two yaml files in the ${cluster_name}  dir so I just specify the ${cluster_name} dir for kubectl.

**Comment by DanielZhangQD** [comment]
@coderplay Could you please show me the error log when you run the command?

**Comment by ran-huang** [comment]
Any update on this issue?
