### ISSUE TITLE
升级tidb operator之后？

### ISSUE THREAD

**Issue by coderplay** [pingcap/docs-tidb-operator#266]
File: [/zh/upgrade-tidb-operator.md](https://pingcap.com/docs-cn/tidb-in-kubernetes/v1.1/upgrade-tidb-operator/)

Q1: 怎么确定升级operator成功？换句话说，怎么确定我的operator在版本1.1
Q2: 升级operator之后是否对已存在tidb cluster作变化？ 如果没有变化，如何升级现有的tidb cluster?

**Comment by DanielZhangQD** [comment]
> File: [/zh/upgrade-tidb-operator.md](https://pingcap.com/docs-cn/tidb-in-kubernetes/v1.1/upgrade-tidb-operator/)
> 
> Q1: 怎么确定升级operator成功？换句话说，怎么确定我的operator在版本1.1
> Q2: 升级operator之后是否对已存在tidb cluster作变化？ 
上面两个问题我们会更新一下文档
> 如果没有变化，如何升级现有的tidb cluster?
这个不管有没有变化都请参考 tidb cluster [升级文档](https://pingcap.com/docs-cn/tidb-in-kubernetes/stable/upgrade-a-tidb-cluster/)

**Comment by ran-huang** [comment]
Any update on this issue?
