### ISSUE TITLE
逻辑矛盾？

### ISSUE THREAD

**Issue by coderplay** [pingcap/docs-tidb-operator#267]
File: [/zh/notes-tidb-operator-v1.1.md](https://pingcap.com/docs-cn/tidb-in-kubernetes/v1.1/notes-tidb-operator-v1.1/)

从 TiDB Operator v1.1.0 开始，`PingCAP 不再继续更新维护 tidb-cluster chart`，原来由 tidb-cluster chart 负责管理的组件或者功能在 v1.1 中的变更如下：

但后面的文字与上一句矛盾

`tidb-cluster chart 仍然会继续发布，但是不再添加新功能`，比如组件 TLS（目前只是部分支持）、TiKV 和 TiDB 自动伸缩等功能。

**Comment by DanielZhangQD** [comment]
这里的意思 pingcap 不再给它添加新功能了，但是有可能社区还会添加新功能，所以还会继续发布，我们看一下再修改的更明确一些。
