### ISSUE TITLE
Add a document that how to install tidb-operator and deploy tidb cluster offline

### ISSUE THREAD

**Issue by weekface** [pingcap/docs-tidb-operator#377]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

- [ ] https://github.com/pingcap/docs-tidb-operator/pull/378

**Comment by ran-huang** [comment]
@weekface Can we close this issue now? To my knowledge, the related docs are already updated.
