### ISSUE TITLE
Move tidb-operator architecture section to a new page

### ISSUE THREAD

**Issue by cofyc** [pingcap/docs-tidb-operator#386]
Move https://pingcap.com/docs/tidb-in-kubernetes/stable/tidb-operator-overview/#tidb-operator-architecture to a new page under architecture section.

**Comment by TomShawn** [comment]
@ran-huang PTAL thanks!

**Comment by cofyc** [comment]
This is a track issue for my task assigned in an internal doc.

**Comment by TomShawn** [comment]
> This is a track issue for my task assigned in an internal doc.

OK
