### ISSUE TITLE
Update overview page to reflect latest changes in v1.1

### ISSUE THREAD

**Issue by cofyc** [pingcap/docs-tidb-operator#387]
ref: https://pingcap.com/docs-cn/tidb-in-kubernetes/stable/tidb-operator-overview/

**Comment by ran-huang** [comment]
Is this already covered in [what's new in v1.1](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/whats-new-in-v1.1)?

btw, I think it's high time that we move the release notes to our docs webiste.
@DanielZhangQD WDYT?

**Comment by DanielZhangQD** [comment]
> Is this already covered in [what's new in v1.1](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/whats-new-in-v1.1)?

It's covered in https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/tidb-operator-overview.

> btw, I think it's high time that we move the release notes to our docs webiste.
> @DanielZhangQD WDYT?

What's your suggestion about maintaining the release notes?

- No need to keep in the tidb-operator repo and we migrate all of them to the docs repo?
- Do we need to add a Chinese version?

**Comment by ran-huang** [comment]
> What's your suggestion about maintaining the release notes?
> - No need to keep in the tidb-operator repo and we migrate all of them to the docs repo?
> - Do we need to add a Chinese version?

- Migrate all of them to the docs repo, as we do for [TiDB](https://github.com/pingcap/docs/tree/master/releases) and [DM](https://github.com/pingcap/docs-dm/tree/master/en/releases).
- No need to provide a Chinese version for now. If users want a Chinese version, we can add it later.

@DanielZhangQD what do you suggest?
