### ISSUE TITLE
"Collect TiDB Logs in Kubernetes" does not chinese version?

### ISSUE THREAD

**Issue by cofyc** [pingcap/docs-tidb-operator#392]
https://github.com/pingcap/docs-tidb-operator/blob/master/en/collect-tidb-logs.md

**Comment by DanielZhangQD** [comment]
It's moved to https://pingcap.com/docs-cn/tidb-in-kubernetes/stable/logs-collection/ and is not synced to English version yet.

**Comment by ran-huang** [comment]
FYI, the English PR is still under review: https://github.com/pingcap/docs-tidb-operator/pull/459
