### ISSUE TITLE
增加对{cluster_name} 的描述

### ISSUE THREAD

**Issue by jacktd9** [pingcap/docs-tidb-operator#401]
集群的yaml metadata:name: test = 监控的yaml spec:clusters: name: test，这点可以多点阐述吗，有时候刚上手还是有点不解的

**Comment by TomShawn** [comment]
@liuxuefeng12 可否提供一下相应的文档链接呢？

**Comment by liuxuefeng12** [comment]
集群：
https://github.com/pingcap/tidb-operator/blob/master/examples/basic/tidb-cluster.yaml
![image](https://user-images.githubusercontent.com/63033738/84561455-24519680-ad7f-11ea-9494-3bfef03994ce.png)

监控：
https://github.com/pingcap/tidb-operator/blob/master/examples/monitor-with-externalConfigMap/tidb-monitor.yaml
![image](https://user-images.githubusercontent.com/63033738/84561470-421efb80-ad7f-11ea-9de1-0e02d72d351d.png)
name都设置一样的时候没察觉，但是有时候需要设置不同的时候对于name的辨别可能会有错误的理解

**Comment by TomShawn** [comment]
@DanielZhangQD PTAL, thanks!

**Comment by DanielZhangQD** [comment]
https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/monitor-using-tidbmonitor
这里面有注意事项：
![image](https://user-images.githubusercontent.com/36026334/94220626-fa7e4300-ff1b-11ea-9673-8dd24c7bcafc.png)
