### ISSUE TITLE
binlog 监控无数据

### ISSUE THREAD

**Issue by Bowen-Tang** [pingcap/docs-tidb-operator#403]
binlog 部署好测试正常后，发现 binlog 监控面板没有数据

**Comment by TomShawn** [comment]
@Bowen-Tang 可否提供相关的文档链接呢？如何和文档无关，建议在 [TiDB Binlog](https://github.com/pingcap/tidb-binlog/issues) repo 下提 issue。

**Comment by DanielZhangQD** [comment]
Fixed in https://github.com/pingcap/tidb-operator/pull/2750
