### ISSUE TITLE
照着文档，无法生成 local-storage

### ISSUE THREAD

**Issue by aslzl** [pingcap/docs-tidb-operator#418]
File: [/zh/configure-storage-class.md](undefined/zh/tidb-in-kubernetes/v1.1/configure-storage-class)

文章【Kubernetes 上的持久化存储类型配置】下，标题【本地 PV 配置】下 运行
kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/local-dind/local-volume-provisioner.yaml 

运行后，验证 pod 运行正常，但 PV 没有生成，是否要在文档下给出原因及 解决方案

**Comment by cofyc** [comment]
这部分文档是需要更完善一点。

是否在 /mnt/disks (也就是这个 yaml 默认制定的本地存储路径) 下创建本地存储？这个程序是用来发现和管理机器上配置本地存储。
