### ISSUE TITLE
zh: align get started tutorial

### ISSUE THREAD

**Issue by cofyc** [pingcap/docs-tidb-operator#433]
https://github.com/pingcap/docs-tidb-operator/pull/362
https://github.com/pingcap/docs-tidb-operator/pull/405
https://github.com/pingcap/docs-tidb-operator/pull/406
#437
#439 
#453
#460
https://github.com/pingcap/docs-tidb-operator/pull/496

**Comment by cofyc** [comment]
@ran-huang can you help translate recent changes to get started tutorial and align the structure?

**Comment by ran-huang** [comment]
@cofyc I'm now occupied in translating many Chinese docs in this repo to English.
I just discussed with @DanielZhangQD this afternoon and asked for his help with the translation from English to Chinese. I'll help review when it's ready😄
