### ISSUE TITLE
Improve the backup and restore doc

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#488]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

Backup & Restore 
- Overview
  - 需要提一下Scenarios -- link to logical and physical backup & restore
- Grant Permissions to Remote Storage
  - S3
  - GCS
- Backup with Dumpling
  - Backup to S3
  - Backup to GCS
- Restore with TiDB Lightning
  - Restore from S3
  - Restore from GCS
- Backup with BR
  - Backup to S3
  - Backup to GCS
  - Backup to NFS
- Restore with BR
  - Restore from S3
  - Restore from GCS
  - Restore from NFS

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by ran-huang** [comment]
The new structure looks good.
I have a few questions: 
- What's the relationship between logical and physical backup? 
- How do they correspond to different tools (BR, Dumpling, etc.)?

**Comment by DanielZhangQD** [comment]
We should also optimize the docs to remove the duplicate contents.
