### ISSUE TITLE
Provide procedures to scale up TiKV clusters using local disks to another node pool

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#552]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
There are cases where users are running TiKVs using local disk in one node pool e.g. with 8 CPUs but want to migrate to another node pool with more cpus, e.g. 16 CPUs.
We have to provide procedures to instruct users to migrate.

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by DanielZhangQD** [comment]
@cofyc @weekface @lichunzhu WDYT?

**Comment by cofyc** [comment]
gke, or all cloud providers (aws, gke, aliyun)?

**Comment by cofyc** [comment]
I think it's useful but has a low priority compared to other issues in current docs.

**Comment by DanielZhangQD** [comment]
The user reports this issue is using GKE, but I think we have to cover EKS at least.
And @zhexuany would like to submit for PR for this, then we can review.

**Comment by DanielZhangQD** [comment]
Also in some cases, users want to migrate to nodes with better disks, e.g. nodes with HDD to nodes with SSD, we can provide a similar procedure as https://docs.pingcap.com/tidb-in-kubernetes/dev/migrate-tidb-to-kubernetes#step-2-create-a-tidb-cluster-in-kubernetes, just create another tc, set the `spec.pdAddress`  to the pd address of the original tc, then they will become one whole tidb cluster, and we can scale in the components in the original tc manually.

**Comment by DanielZhangQD** [comment]
Also, even if with EBS, users may want to shrink the EBS volume size.
