### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by neilydhan** [pingcap/docs-tidb-operator#554]
File: [/en/deploy-on-gcp-gke.md](undefined/tidb-in-kubernetes/stable/deploy-on-gcp-gke)

When running ./create-service-account.sh 
Will encounter the following error,
creating a new service account terraform
ERROR: (gcloud) The project property must be set to a valid project ID, not the project name [
macro-griffin-333333

Had to use command line to create service account.

**Comment by ran-huang** [comment]
@DanielZhangQD PTAL

**Comment by cofyc** [comment]
what's the output of `env GCP_PROJECT`?

it uses the project set in `GCP_PROJECT` environment. please check if this env is set correctly. 

this script invokes the `gcloud` CLI too. it's fine to create the service account via `gcloud` manually or using the web console.

currently, the following roles are required:

```
  roles/container.clusterAdmin
  roles/compute.networkAdmin
  roles/compute.viewer
  roles/compute.securityAdmin
  roles/iam.serviceAccountUser
  roles/compute.instanceAdmin.v1
```
