### ISSUE TITLE
New EKS deployment guide

### ISSUE THREAD

**Issue by cofyc** [pingcap/docs-tidb-operator#579]
draft: https://docs.google.com/document/d/18-15NjiltD1uSbEvE7IpyOFlPQUKskyyaH5h_pR7-kc/edit?usp=sharing

- using eksctl
- using network-attached PVs (no local volume provisioner etc)
- no user-data script
  - without local PVs, we don't need to format & mount local PVs
  - `max open files` is already 1048576 by default
- using  helm 3 (helm 2 is old and hard to use)
- remove "自定义" sections
  - but may add instructions on how to add a new node group to deploy TiFlash, etc.

**Comment by cofyc** [comment]
@DanielZhangQD 
these are my primary goals, PTAL. I'm working on the PR.

**Comment by DanielZhangQD** [comment]
> no user-data script
> without local PVs, we don't need to format & mount local PVs

We have to include the procedure that if users want to use local PVs, what they should do.

> max open files is already 1048576 by default

Please make sure that https://github.com/pingcap/tidb-operator/blob/master/deploy/modules/aws/tidb-cluster/templates/userdata.sh.tpl#L6-L23 these configurations are covered or confirm if it's OK without configuring them.

BTW, please also cover the reasonable parts mentioned [here](https://github.com/pingcap/tidb-operator/issues/2787#issuecomment-657560124).
For the `suspended_processes`, I think it's ok not to configure it if not using local SSD, but if users use local SSD, we may have to configure it.

**Comment by cofyc** [comment]
> Please make sure that https://github.com/pingcap/tidb-operator/blob/master/deploy/modules/aws/tidb-cluster/templates/userdata.sh.tpl#L6-L23 these configurations are covered or confirm if it's OK without configuring them.

not needed anymore.

I'm ok to provide an optional local PVs setup.
