### ISSUE TITLE
Corrupt markdown format at "Kubernetes 上使用 TiDB Operator 快速上手" Chapter

### ISSUE THREAD

**Issue by LENSHOOD** [pingcap/docs-tidb-operator#646]
File: [/zh/get-started.md](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/get-started)

Corrupt format location:
- Chapter -- "Kubernetes 上使用 TiDB Operator 快速上手"
  - Section -- "部署 TiDB Operator"
    - Subsection -- "安装 TiDB Operator"
      - Subsection -- "iv. 安装 TiDB Operator"

The "Helm 3" paragraph seems mixed with "Helm 2" lead to markdown format cannot be displayed correctly.

However, the [md source](https://github.com/pingcap/docs-tidb-operator/blob/master/zh/get-started.md) displayed all good at github and typora.

**Comment by ran-huang** [comment]
Thank you for pointing out!😀
It is caused by an extra blank line in the code block. We'll fix it as soon as possible.

**Comment by ran-huang** [comment]
The issue is fixed! That page should be normal in a few minutes. You can also force a refresh by pressing <kbd>cmd</kbd>/<kbd>control</kbd>+<kbd>shift</kbd>+<kbd>R</kbd>.
Thank you again 🎉

**Comment by LENSHOOD** [comment]
Awesome! :beers: :beers: :beers:
