### ISSUE TITLE
Doc update for monitoring multiple TiDB clusters with one TidbMonitor

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#751]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

https://github.com/pingcap/tidb-operator/pull/3308 supports monitoring multiple TiDB clusters with one TidbMonitor with TLS disabled. The doc https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/monitor-using-tidbmonitor needs to be updated.
2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by ran-huang** [comment]
@DanielZhangQD Is this issue resolved?
