### ISSUE TITLE
Operator version

### ISSUE THREAD

**Issue by kidrocknroll** [pingcap/docs-tidb-operator#77]
## Question

I have read the document about [prerequisites](https://github.com/pingcap/docs-tidb-operator/blob/master/en/prerequisites.md)... It shows that the minimum version of Kubernetes cluster is v1.12.5 and the minimum version of docker-ce is 18.09.6.

I Got a cluster which is v.1.12.4, docker-ce which is 18.06.3 and neither of them supports upgrade... So can I use the operator in the cluster? What effect do these differences take?

**Comment by ran-huang** [comment]
@DanielZhangQD PTAL~

**Comment by DanielZhangQD** [comment]
@kidrocknroll v1.12.5 is the minimum version that we have tested with.
For the docker version, there is a known issue for `kmem account`, which you can refer to https://mp.weixin.qq.com/s/Ee9R5H0Qbkgwf0fR_2rrHQ for more detail.

Please note that the issues mentioned in the above article are not for TiDB Pods only but for all to the containers in your Kubernetes cluster.

**Comment by kidrocknroll** [comment]
@Damon-PingCap Thx for your time ~
