### ISSUE TITLE
wrong link url in deploy-tiflash.md

### ISSUE THREAD

**Issue by dragonly** [pingcap/docs-tidb-operator#805]
## Error Report

link for "新增部署 TiFlash" is wrong.

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/deploy-tiflash

2. How would you like to improve it?

**Comment by TomShawn** [comment]
@DanielZhangQD PTAL, thanks!

**Comment by dragonly** [comment]
#806
