### ISSUE TITLE
Use the coincide version CR files

### ISSUE THREAD

**Issue by july2993** [pingcap/docs-tidb-operator#828]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-on-aws-eks

It's using the master branch's CR files
curl -LO https://raw.githubusercontent.com/pingcap/tidb-operator/master/examples/aws/tidb-cluster.yaml &&
curl -LO https://raw.githubusercontent.com/pingcap/tidb-operator/master/examples/aws/tidb-monitor.yaml

2. Describe your suggestion or addition.
Use the coincide version CR files
3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by TomShawn** [comment]
@DanielZhangQD PTAL, thanks!

**Comment by DanielZhangQD** [comment]
Will be fixed in https://github.com/pingcap/docs-tidb-operator/pull/802.

**Comment by july2993** [comment]
> Will be fixed in #802.

still use master in the pick pr https://github.com/pingcap/docs-tidb-operator/pull/836/files

**Comment by ran-huang** [comment]
Fixed in https://github.com/pingcap/docs-tidb-operator/pull/839
