### ISSUE TITLE
Add doc for ad-hoc mod for Lightning

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#862]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

The data import with tidb-lightning chart supports the following three modes:

- local
- remote
- ad-hoc https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-lightning/values.yaml#L26-L28

However, the ad-hoc mod is not covered in the current doc https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/restore-data-using-tidb-lightning, which needs to update.
2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by csuzhangxc** [comment]
@DanielZhangQD we remove backup data after archived (https://github.com/pingcap/tidb-operator/blob/6b44131af7eb94acb8cdaadf1e8847ba01200922/cmd/backup-manager/app/export/manager.go#L322) and remove archived data after uploaded to remote (https://github.com/pingcap/tidb-operator/blob/6b44131af7eb94acb8cdaadf1e8847ba01200922/cmd/backup-manager/app/export/manager.go#L350).

so, I think ad-hoc should not work now. Should we need to:

- add an option to keep the backup data locally for ad-hoc
- or remove ad-hoc support in the code

**Comment by DanielZhangQD** [comment]
@csuzhangxc It's still useful with the current behavior. We have a user that has 16 TB backup, and it may take 48 hours to download the files from S3, and then the import with tidb-lightning failed, in this case, we can reuse the PVC, and no need to download the files again.

> add an option to keep the backup data locally for ad-hoc

For this, we can support it if some users request this later, WDYT?

**Comment by csuzhangxc** [comment]
OK. I'll update docs for the case you mentioned above.

> For this, we can support it if some users request this later, WDYT?

SGTM
