### ISSUE TITLE
Can we delete the content about "tkctl"(or refactor it)?

### ISSUE THREAD

**Issue by grandsail** [pingcap/docs-tidb-operator#908]
Since the tool "tkctl" will no longer be usable, can we delete the content about it?
I got to know "tkctl" in the content about "maintaining a K8S node", and it is marked as "prerequisites". 
en: https://docs.pingcap.com/tidb-in-kubernetes/stable/maintain-a-kubernetes-node#prerequisites
zh: https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/maintain-a-kubernetes-node#%E7%BB%B4%E6%8A%A4-tidb-%E9%9B%86%E7%BE%A4%E6%89%80%E5%9C%A8%E7%9A%84-kubernetes-%E8%8A%82%E7%82%B9
And there is the introduction of "tkctl"
en:https://docs.pingcap.com/tidb-in-kubernetes/stable/use-tkctl
zh: https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/use-tkctl

BTW: 
It seems that the "tkctl" tool is realized with Golang now, can we realize it with the Bash language? There are lots of situations in which we **really need** a easier way to get the information about a TiDB cluster in K8S cluster.  
For example, to know which TiDB Pod (TiDB/TiKV/PD) is allocated on which nodes and the ports asigned to them, we need to use lots of `kubectl get pods` and `kubectl describe node` commands. If we have a bash program (there is no need to use a Golang program) helping us to use the kubectl commands and understand them, lots of time will be saved. And maybe we can rename the program as "tkctl"?

@Kumson Sorry that we have not maintained the `tkctl` tool for a long time, actually from v1.1.x, we recommend to use kubectl directly, you can use `kubectl get tc -A` to list all the clusters.

_Originally posted by @DanielZhangQD in https://github.com/pingcap/tidb-operator/issues/3577#issuecomment-740490011_

**Comment by ran-huang** [comment]
Thank you for the feedback!
@DanielZhangQD Let's mark `tkctl` as `deprecated` or `not recommended` in our docs. WDYT?

**Comment by Kumson** [comment]
> Thank you for the feedback!
> @DanielZhangQD Let's mark `tkctl` as `deprecated` or `not recommended` in our docs. WDYT?

It will be better to mark it as `deprecated` or `not recommended` in docs for now.(It's kind of confusing now)
But I think we still need to maintain a tool with similar functions in the future.

**Comment by grandsail** [comment]
@ran-huang Hi, parhaps I can take the job to edit the content about "tkctl" in the docs? And you can review the changes.
(I observed that you and Daniel are all occupied with the development of other projects.)

**Comment by ran-huang** [comment]
Thanks in advance 😸 
You can comment `/assign` to claim this issue.

After you create a PR, you can also comment `/cc ran-huang, DanielZhangQD` in the PR to request our review~ Much appreciated.

**Comment by DanielZhangQD** [comment]
@grandsail Thanks a lot for updating the docs!

> But I think we still need to maintain a tool with similar functions in the future.

For this requirement, we may not be able to provide it recently, would you like to write one according to your requirements and contribute to the tidb-operator repo?
Then the community can continue to improve it.
