### ISSUE TITLE
Should we add more detailed introduction about "tidb.service" at the section of "Configure TiDB Cluster"?

### ISSUE THREAD

**Issue by grandsail** [pingcap/docs-tidb-operator#911]
1. Describe what you find is inappropriate or missing in the existing docs.
en: https://docs.pingcap.com/tidb-in-kubernetes/stable/configure-a-tidb-cluster#configure-tidb-deployment
zh: https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/configure-a-tidb-cluster#%E9%83%A8%E7%BD%B2%E9%85%8D%E7%BD%AE
At this point, we need to correctly configure `spec.tidb.service` (whether using ClusterIP, NodePort or LB). Otherwise, at the step of "Initialize TiDB Cluster", the Pod named "tidb-initializer" wont complete as expected. The reason is that the "tnir/mysqlclient" container failed to connect tidb service. You can check the situation I met at here https://asktug.com/t/topic/63767
**Why I didn't use the `spec.tidb.service` field at first?**
I am new in TiDB and Kubenetes, so I checked the example and API document. (Maybe an expeerienced Kubenetes user will avoid this error)
example: https://github.com/pingcap/tidb-operator/blob/4f0d096e4177a3458b231cf62bd8b08afa09c7dd/examples/advanced/tidb-cluster.yaml#L118
API document: https://github.com/pingcap/tidb-operator/blob/master/docs/api-references/docs.md#tidbspec
In the links above, you will find that the `spec.tidb.service` field is annotated in the example and marked "optional" in the API document. So I didn't use it at first, but failed at the step of "Initialize TiDB Cluster"

2. Describe your suggestion or addition.
In the section of "Initialize TiDB Cluster" in the docs, there is detailed introduction of ClusterIP, NodePort and LB. Should we put such information in front of users at the section of "Configure TiDB Cluster"?

**Comment by ran-huang** [comment]
Many thanks for the detailed feedback 😸 
We'll definitely look into it.

**Comment by DanielZhangQD** [comment]
@grandsail Thanks for reporting this issue!
@BinChenn Please help follow up on this issue, thanks!
