### ISSUE TITLE
What version of Helm do we recommend?

### ISSUE THREAD

**Issue by ran-huang** [pingcap/docs-tidb-operator#953]
In [Get Started](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/get-started#%E9%83%A8%E7%BD%B2-tidb-operator):

```
开始之前，确保以下要求已满足：

- 可以使用 kubectl 访问的 Kubernetes 集群
- 已安装 Helm 3
```

In [Production deployment](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/deploy-tidb-operator#%E5%87%86%E5%A4%87%E7%8E%AF%E5%A2%83) and [TiDB Toolkit](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/tidb-toolkit#%E4%BD%BF%E7%94%A8-helm):

```
TiDB Operator 部署前，请确认以下软件需求：

- .....
- Helm 版本 >= 2.11.0 && < 3.0.0 && != 2.16.4
```

Do we recommend Helm 2 or Helm 3?

**Comment by ran-huang** [comment]
@DanielZhangQD

**Comment by DanielZhangQD** [comment]
We will submit PR to support Helm 3 for the current docs later.

**Comment by ran-huang** [comment]
Closing this issue because it duplicates with https://github.com/pingcap/docs-tidb-operator/issues/869
