### ISSUE TITLE
A procedure to renew CA when CA generated by cert-manager expires

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#982]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

Currently, cert-manager does not support to renew the CA automatically, please check the detail in https://github.com/jetstack/cert-manager/issues/2478, we have to check if it's possible to do this manually before cert-manager supports this.

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by ran-huang** [comment]
@DanielZhangQD @csuzhangxc Is this issue closed by #1026?

**Comment by DanielZhangQD** [comment]
> @DanielZhangQD @csuzhangxc Is this issue closed by #1026?

@ran-huang Yes, we can close this issue now, thanks!
