### ISSUE TITLE
Add doc for canary upgrade of TiDB Operator

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/docs-tidb-operator#992]
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
Related PR https://github.com/pingcap/tidb-operator/pull/3548

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by DanielZhangQD** [comment]
@shonge Please help take this issue, thanks!

**Comment by cvvz** [comment]
1. If one of operators set `admissionWebhook.create=true`,  all the other operator will be influenced by this admission webhook.
2. It is not supported that some operators enable the feature of `AdvancedStatefulSet` while others not.

**Comment by DanielZhangQD** [comment]
https://github.com/pingcap/docs-tidb-operator/pull/1043 focuses on the procedure to deploy multiple TiDB Operators.
We need another PR to provide the procedure for the canary upgrade.
